### ISSUE TITLE
Initialise bird's data members

### ISSUE THREAD

**Issue by priyanshisharma** [GirlScript-Ireland/Gaming-Booster#19]
We look at our bird, like a ball for now. An upward force, will make it go up, and downward force will push it down. This requires the bird to possess certain attributes like velocity, acceleration et cetera. Initialising them as follows:

1.  Define the following in the `Bird` class.
(i) `PVector acc;`
(ii) `PVector vel;`

2. Initialise them in the constructor as follows
(i) `vel = new PVector(0, 0); `
(ii) `acc = new PVector();`

3. Create an `update` function with `void` return type to update these physical quantities. Update them inside the function as follows;
(i) `pos.add(vel);` in order to update the position with respect to velocity
(ii) `vel.add(acc);` in order to update the velocity as per acceleration.
(iii) `vel.limit(4);` in order to cap the velocity for a smooth run.

4. Call the `update` function before `b.show();` as `b.update();` in `flappy_bird.pde`.

**Comment by ExpressHermes** [comment]
I am solving this issue
