### ISSUE TITLE
Give Bird Downward acceleration

### ISSUE THREAD

**Issue by priyanshisharma** [GirlScript-Ireland/Gaming-Booster#20]
This needs to be solved only after #19 .

1. We need the bird to have a habitual downward movement, due a force similar to *Gravity*. **Since, gravity is a property of the environment and not the bird**. 
* Initialise the gravity in `flappy_bird.pde` as `PVector gravity = new PVector(0,0.5);`.

2. Since we will need to apply force multiple times on the bird, it is nice to define a function for the same in `bird.pde`. So, 
* Within the `class Bird` create a function `applyForce` with `void` return type, and takes `PVector force` as argument. 
* Increase the acceleration using the statement `acc.add(force);` inside the function.

3. To habitually apply gravity, add `applyForce(gravity);` in the first line of `update` function of the `class Bird`.

**Comment by ExpressHermes** [comment]
I am solving this issue
