### ISSUE TITLE
Give Bird Upward acceleration and limit Movement

### ISSUE THREAD

**Issue by priyanshisharma** [GirlScript-Ireland/Gaming-Booster#21]
To be solved only after #19 and #20 

You may notice that the bird tends to keep going downwards past the canvas. We want to prevent that, for the same we do the following.
(i) In the `update` function of `class Bird`, check the position using the if condition `if(pos.y >=height)`
(ii) Inside the if block specify the exact position such that the ball doesn't go any lower by writing `pos.y=height;`.
(iii) Since the position is constant set velocity to be zero in here itself by writing `vel.mult(0);`

Congratulations on completing the Bird class 🐦 🎉 

To check if a key has been pressed and act accordingly you need to work on `flappy_bird.pde`.
(i) In the `draw` function, write an if statement as  `if (keyPressed)`.
(ii) Declare the upward acceleration as `PVector up = new PVector(0, -5);` inside the if block.
(iii) Update the acceleration using `b.applyForce(up);`.

**Comment by vridhi-vk** [comment]
will work on this
