### ISSUE TITLE
Detect Bird and Barrier Collision

### ISSUE THREAD

**Issue by priyanshisharma** [GirlScript-Ireland/Gaming-Booster#23]
1. Declare a function named `hits` with `boolean` return type. Return the following statement `return ((b.pos.x > x)&&(b.pos.x < (x+wid)))&&((b.pos.y < (top + b.r)) || (b.pos.y > (height - bottom - b.r)));`
**Explanation**

The above statement breaks down to
* if the x-coordinate falls in the width of the barrier by `((b.pos.x > x)&&(b.pos.x < (x+wid)))`
* if the y-coordinate falls across the diameter of the circle by `((b.pos.y < (top + b.r)) || (b.pos.y > (height - bottom - b.r)))`
is joined using **&&** i.e. if both stated conditions are `true`, only then the statement evaluates as `true` else it is `false`. This may also be broken down as:
```
if ((b.pos.x > x) && (b.pos.x < (x + w)))
    {
      if ((b.pos.y < (top + b.r)) || (b.pos.y > (height - bottom - b.r))) 
      {
        return true; 
      }
    }
    return false;
```
2. We want to display the barrier differently on being hit. We can do that by passing `boolean hit` as a parameter to the `show` function of the barrier and change the colour with a simple if else block like
```
if(hit)
{
    fill(217, 74, 30,127);
}
else{
      fill(65,224,129,127); 
}
```

Congratulations on completing the `barrier.pde`! 🖊️ 🎉

**Comment by karolade** [comment]
I will work on this!
