### ISSUE TITLE
Display the Barriers

### ISSUE THREAD

**Issue by priyanshisharma** [GirlScript-Ireland/Gaming-Booster#24]
Solve only after #22 and #23 

At the end of the `draw` function, create a for loop to traverse the `ArrayList` of barriers as  `for (int i = barriers.size() - 1; i >= 0; i--)`. Inside the for loop add the the following
1. Fetch a barrier by `Barrier p = barriers.get(i);`
2. Update the fetched barrier as `p.update();`.
3. if the bird hits the barrier(check using the `hits` function created), pass `true` in `show` function else `false` as follows:
```
if (p.hits(b)) 
    {
      p.show(true);
    }
    else
    {
      p.show(false);
    }
```
4. Delete the pipes that go outside the frame by adding the following if condition in the loop.
```
if (p.x < -p.w)
    {
      pipes.remove(i);
    }
```

**Comment by ExpressHermes** [comment]
I will work on this
