### ISSUE TITLE
Add Score

### ISSUE THREAD

**Issue by priyanshisharma** [GirlScript-Ireland/Gaming-Booster#25]
1. Initialise the integer score variable in `flappy_bird.pde` as `int score = 0;`.
2. Initialise a boolean variable `safe` to keep track of the ball. Initialise it to true as we assume that the ball doesn't hit a barrier as soon as the game starts. Hence, declare `boolean safe = true;`.
3. Modify the if condition of the bird hitting the barrier as to update the variable `safe` as `false` when hit a wall as follows;
```
if (p.hits(b)) 
    {
      p.show(true);
      safe = false;
    }
    else 
    {
      p.show(false);
      safe = true;
    }
```
4. Outside the for loop, in the `draw` function update the score variable as follows:
```
 if(safe)
    {
      score++;
    }
    else
    {
      score-=50;
    }
```
5. Hence in the `draw` function, display the text as follows
* Fill the text-colour using `fill(16, 53, 201);`.
* Set the textsize as `textSize(64);`
* Display it at coordinates (width/2,50) as `text(score, width/2, 50);`.
* Ensure the score is always positive using `constrain` function as `score = constrain(score, 0, score);`.

Congratulations on completing flappy bird! 🚀 🐦

**Comment by vridhi-vk** [comment]
Will work on this if everyone have got a chance to

**Comment by priyanshisharma** [comment]
Sure @vridhi-vk , you can proceed with this issue! 👍
