### ISSUE TITLE
Elongate the snake on eating

### ISSUE THREAD

**Issue by priyanshisharma** [GirlScript-Ireland/Gaming-Booster#65]
**Initialise data members**
1. Initialise a `this.tail = [];` to keep track of location of tail squares of the snake
2. Initialise a `this.total = 0;` to keep track of total elements of the tail.

**Update the `eat` function**
1. Everytime food is eaten, `this.total` needs to be incremented. Hence `return d < 0.5` must be replaced by 
```
if (d < 0.5) 
    { 
      this.total++;
      return true;
    } 
    else 
    {
      return false; 
    }
```

**Update the `show` function**
1. At the end, write a for loop that loops from 0 to `this.tail.length` and displays the snake's tail elements as `rect(this.tail[i].x,this.tail[i].y,scl,scl);`.

**Update the `update` function**
1. To move forward, assign locations of `i+1`th tail element by `i`th tail element by running a for loop from 0 to `this.tail.length-1` and write `this.tail[i] = this.tail[i + 1];`.
2. Since the vector at the last position goes away in the the above method, using the statement below.
```
if (this.total >= 1) 
    {
      this.tail[this.total - 1] = createVector(this.x, this.y);
    }
```

**Comment by vridhi-vk** [comment]
working on this :)
