### ISSUE TITLE
Add Death function

### ISSUE THREAD

**Issue by priyanshisharma** [GirlScript-Ireland/Gaming-Booster#66]
In `snake.js`, 

1. Create a death function as `this.death = function() {}`. Within it:
2. Iterate the tail by saying `for (let i = 0; i < this.tail.length; i++) {}`. Within it:
3. Get position of tail element as `let pos = this.tail[i];`.
4. Find distance between head and tail element as `let d = dist(this.x, this.y, pos.x, pos.y);`.
5. Considering a hit `if(d<1)` set the tail and total to initial values by writing `this.total=0` and `this.tail = []` within the if condition.

In `snake_game.js`

6. Call `s.death();` before `s.update()` in the `draw()` function.

**Comment by ExpressHermes** [comment]
I will be taking this issue
